mozilla/price-tracker

- src/browser_action/components/TrackedProductList.css
- src/browser_action/index.css
The product list now properly overflows, and max heights have been set to match
the Firefox-enforced 600px height limit for popup panels.
> Fix #167, fix #195: Set heights and overflow to fix scrolling.

- .circleci/deploy_addon.sh
- src/browser_action/components/EmptyOnboarding.css
- src/browser_action/index.css
- src/config.js
- src/experiment_apis/shoppingPrefs/api.js
- web-ext-config.js
This is a pile of tiny fixes that I'm comfortable self-reviewing in order to get a new release out tonight:
1. Updates the deploy script to use the correct filename for the add-on file, which changed when we changed the add-on name. The 5.0.0 release failed due to this.
2. Updates the preference subtree for overriding config values to use the new add-on ID; I missed this when switching to the new ID.
3. I missed that the CSS changes earlier today made the empty onboarding view expand to an unreasonable width; the changes in this PR fix the width, and also ensure the onboarding view looks correct when the toolbar icon is pinned to the overflow menu.
> Fix deploy script and other changes.

- .circleci/config.yml
Turns out `ripgrep` doesn't search `.circleci/config.yml` by default, and I missed this. Sigh.
> Fix add-on filename in Circle config as well.

- src/browser_action/components/ProductCard.css
This prevents it from expanding indefinitely, but allows some flex to
accommodate the increased width when pinned to the overflow menu.
> Fix #217: Clamp the sizing of the title/details column.

- src/background/extraction.js
- src/background/index.js
- src/extraction/index.js
- src/extraction/selector/selectors.js
- src/manifest.json
So the BOTW page is being extracted via selector instead of Fathom. One approach would have been to add some rules and include the page in our training, but I opted for the selector-based solution since I'm not set up for training yet and Erik is making some large changes to our ruleset currently.
- Switches selector-based price extraction to use the same method for splitting up price nodes as Fathom does, i.e. taking the text of the immediate children, as the BOTW page has a Home Depot-style price display.
- Adds detection for `pushState` calls in the page that change the page's URL. Since the contents of the page often change during these switches, and since product IDs are based off the URL, we should be re-extracting when this happens.
- Adds a new selector for product images from the …
> Fix Amazon issues with the Breath of the Wild product page.

- src/background/index.js
- src/manifest.json
There's some pending PRs with new URL matches that will need altering, I'll rebase this PR after they land.
> Fix #211: Only inject content scripts into http(s) pages.

- package-lock.json
- package.json
- src/background/extraction.js
- src/state/products.js
- src/utils.js
Making proptype checks work in production isn't really feasible, so we solve the
issue by just not trying!
> Fix #212, fix #71: Validate extracted product data, including URL protocols.

- docs/METRICS.md
- src/telemetry/extension.js
Note that some of the data being included describes situations in which telemetry currently isn't being collected, meaning it will effectively never be sent (e.g. Do Not Track being true). #186 will change that.
> Fix #185: Include privacy context info in telemetry pings.

- src/browser_action/components/EmptyOnboarding.css
- src/browser_action/components/ProductCard.css
- src/browser_action/index.css
In previous PRs (#214, #215 and #218) CSS fixes were added to partially constrain either the whole popup or sections of it, leaving the 'Undo' section out. This patch puts a min-width and max-width on the whole popup, while flexibly sizing all its child containers, ensuring that the fixes applied in previous PRs remain in place.
Unfortunately, the Overflow menu has a width greater than our ideal popup width of 320px per the [UX spec](https://mozilla.invisionapp.com/share/UFNSHAIMT4V#/screens/317130676_Artboard_1), and that width cannot be controlled by a Web Extension, so I have set the max-width to 400px which will ensure the width of the popup doesn't change whether the toolbar button is in the overflow menu or not (previously, it would be one width when opened from the overflow menu …
> Fix #230: Constrain width of entire popup with lower and upper bounds

- docs/METRICS.md
- src/background/extraction.js
- src/background/price_alerts.js
- src/background/price_updates.js
- src/browser_action/components/BrowserActionApp.jsx
- src/browser_action/components/EmptyOnboarding.jsx
- src/browser_action/components/ProductCard.jsx
- src/extraction/index.js
- src/state/prices.js
- src/telemetry/extension.js
Broke this up into a few commits. Also updated the extension's name and telemetry category in `METRICS.md` and added a new Appendix section to explain how to find the probes (mostly for QA).
I don’t like how I get the “previous price” (I refetch `state`) for the `detect_price_change` probe, but I didn't see another way.
> Fix #158: Add non-UI telemetry probes

- src/privacy.js
- src/telemetry/extension.js
- web-ext-config.js
Fixing #183 is possible thanks to issue #184 being resolved.
> Fix #258, Fix #183: Record extension event telemetry by default in all channels

- src/background/index.js
- src/background/price_updates.js
- src/state/products.js
@Osmose , ready for your review!
I have one specific question for you:
- I update the product in the `updateProductWithExtraction` function in `./src/background/price_updates.js`. This seemed like the least amount of code to change to get the job done, but perhaps there's a better approach in terms of code organization that you would recommend?
- One option is to rename `price_updates.js` to `product_updates.js`.
- Another option is to break out the product update portion of the code into a separate function, though I'm not sure where it would live.
Edit: Here is an easy way to test the patch:
1. In `updateProductWithExtracted` in `./src/background/price_updates.js`, Add this line temporarily just before dispatching the new update action (`await …
> Fix #147: Update product information during re-extraction

- src/browser_action/components/StudyFooter.css
@Osmose Ready for your review!
Doorhanger footer styles are not specified in https://design.firefox.com/photon/components/doorhangers.html, nor do I see the colors I believe are correct (https://searchfox.org/mozilla-central/source/browser/themes/linux/browser.css#21-23) in the Photon Colors stylesheet (https://github.com/FirefoxUX/photon-colors/blob/master/photon-colors.css), but I can confirm by looking at the source code and a visual inspection that these are the right colors for the different states of buttons. I asked in slack #dsg (design system guidelines) about this lack of clarity.
> Fix #280: Use Firefox background colors for doorhanger footer

- src/browser_action/index.css
- src/browser_action/index.jsx
- src/experiment_apis/customizableUI/api.js
- src/experiment_apis/customizableUI/schema.json
With CustomizableUI.jsm (via the experimental `browser.customizableUI` API added in #157), it is possible to detect when the browserAction toolbar button is and is not in the Overflow menu.
Because the overflow menu width varies by OS (for example, it is 377px wide on my Mac 10.13 and 425px wide on a Linux 14.04 (see screenshots below for confirmation)), this patch will detect whether or not the toolbar button is in the Overflow menu and adjust the width accordingly.
This fix has the added benefit of allowing us to constrain the non-Overflow menu popup width (which is hopefully the vast majority use case) to the UX spec of 320px where previously we had set it to a max-width of 400px to try to accommodate Overflow menu issues.
**Verified issue on Linux 14.04 (v11.0.0 prior to this patch!) …
> Fix #256: Change popup width in overflow menu

- src/privacy.js
@Osmose , ready for your review!
Update `shouldUpdatePrices` with a check for whether or not the active window is a private window.
I did not add a check for `isActiveWindowPrivate` in `shouldExtract` in `./src/privacy.js`, despite the fact that `browser.extension.inIncognitoContext` r[eturns the "wrong" value for background extraction](https://github.com/mozilla/price-wise/pull/168#discussion_r225766093), because background extraction is gated by the `shouldUpdatePrices` check.
> Fix #177: Disable price polling in Private Browsing windows

- .circleci/config.yml
This will allow us to do release builds of the add-on and send them to QA for testing before we actually upload them.
> Require manual approval to upload XPI files to Test Pilot.

- .circleci/config.yml
Turns out without tag filters the new jobs weren't running when I put up a tag. Whoops.
> Add filters to properly trigger new jobs as part of approval workflow.

- src/browser_action/index.css
This overflow declaration was added in #215, nominally to help deal with
overflow issues when pinned to the overflow menu, but it's not clear how this
particular line helps vs the other changes to the width of the onboarding
view.
My theory on why this is biting us now:
- #256 updated the popup to a fixed width when not in the overflow menu, and a
flexible width when it is.
- When we have more items than the 600px max height in the popup, we overflow
and add a vertical toolbar inside.
- The vertical toolbar increases the desired width of the popup, causing the
body element to add a horizontal scrollbar.
- The horizontal scrollbar increases the height beyond the 600px limit (since
the initial overflow is contained within the product listing), causing the
body element to add a vertical …
> Fix #290: Do not allow scrollbars on the entire popup itself.

- docs/METRICS.md
- src/browser_action/components/EmptyOnboarding.jsx
Also update METRICS.md to add the `'amazon_smile_link'` value for the `element` extra key for the `open_nonproduct_page` event, since that was part of the string change request as well.
@Osmose ready for your review!
> Fix #266: Update onboarding string to note support for U.S. domains only

- src/config.js
@Osmose Ready for your review!
I checked this (on Mac OS) for all channels (Nightly, Beta and Release) to ensure the list displays properly still without the footer in light of previous scrollbar/overflow display issues.
----
Per sharonbautista in #274, this can now be removed. However, also per sharonbautista, it is possible we will want to recruit study participants from the extension in the future, so I have just turned the feature flag off in config rather than completely reverting PR#278.
> Remove UR study UI

- docs/METRICS.md
- src/browser_action/components/BrowserActionApp.css
- src/browser_action/components/BrowserActionApp.jsx
- src/browser_action/components/EmptyOnboarding.jsx
- src/config.js
Not much point in linking to a page that doesn't exist anymore. I already checked with product and they're fine with this.
> #302: Remove links to deleted SUMO page.

- .circleci/config.yml
- .circleci/deploy_addon.sh
- README.md
- docs/METRICS.md
- package-lock.json
- package.json
- src/browser_action/components/BrowserActionApp.css
- src/browser_action/components/BrowserActionApp.jsx
- src/browser_action/components/EmptyOnboarding.jsx
- src/browser_action/components/StudyFooter.jsx
- src/browser_action/components/StudyInvitation.jsx
- src/browser_action/index.html
- src/config.js
- src/img/feedback.svg
- src/intro.html
- src/manifest.json
@javaun , @chuckharmston Requesting your approval on the following noteworthy items:
- Alternatives (feedback form):
- Teon updates the URL/survey page and we update it here in the extension.
- We leave the survey and UI as-is
---
Find and replace all instances of "Price Wise", "price-wise" and "price_wise" (case insensitive) with the following exceptions:
* The telemetry event category, 'extension.price_wise' for continuity.
* The survey URLs (for [feedback](https://qsurvey.mozilla.com/s3/price-wise) linked to in the popup and the now flagged off [UR study](https://qsurvey.mozilla.com/s3/Price-Wise-Research-Study)).
Note: Updating the name of the project in `package.json` and calling `npm install` also triggered adding an additional …
> Change name to Price Tracker

- docs/issue_template.md
This template will load any time a new issue is created to (hopefully) ensure some basic information is provided about the issue.
This is based on the [issue template in the `web-ext` repo](https://github.com/mozilla/web-ext/blob/master/ISSUE_TEMPLATE.md) and the [related GitHub docs](https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository).
> Create issue template
